# These flags are no longer needed, since native Wayland and hardware video decoding work out of the box, at least for me and at least as of Chromium 143.
--enable-features=MiddleClickAutoscroll,UseOzonePlatform,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder
--disable-features=WaylandFractionalScaleV1
--ozone-platform=wayland
--force-device-scale-factor=1.0
