format = """
[╭](fg:current_line)\
$time\
$directory\
$git_branch\
$fill\
$nodejs\
$dotnet\
$python\
$java\
$c\
$cmd_duration\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#E3E3E3'
background = '#282A36'
current_line = '#44475A'
box = '#313131'
orange = '#FFB86C'
red	= '#FF5555'
yellow = '#F1FA8C'

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = '[─](fg:current_line)[](fg:box)[󰷏 ](fg:red bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'

[git_branch]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[nodejs]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 Node.js'

[dotnet]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'

[python]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' python'

[java]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Java'

[c]
format = '[─](fg:current_line)[](fg:box)[$symbol](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' C'

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:box)[ ](fg:red bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[time]
format = '(fg:current_line)[](fg:box)[ ](fg:red bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[character]
format = """
[│](fg:current_line)
[╰─$symbol](fg:current_line) """
success_symbol = '[λ](fg:bold white)'
error_symbol = '[×](fg:bold red)'
